### ISSUE TITLE
Ubuntu widevine error

### ISSUE THREAD

**Issue by thomonz** [matthuisman/plugin.video.tvnz.ondemand#1]
HI Matt
Thanks for the Addon works well on a RaspberryPi4.  however when I tried it on by Ubuntu Bionic beaver it kept saying "widevine install error"  I tracked down the issue in the WVhelper.py.  I commented out the last raise error and replaced it with a return.  not ideal but it's now working ok
May help someone else.

Thanks
Karl

**Comment by matthuisman** [comment]
None of my addons use wvhelper....
